# Dockerfile.dev

FROM node:18-alpine

WORKDIR /app

# Copy package.json
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . ./

# Expose the port Vite runs on
EXPOSE 3000

# Command to run the Vite development server
CMD ["npm", "run", "dev"]
