# Dockerfile.dev

FROM node:18-alpine

WORKDIR /app

# Copy package.json
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . ./

EXPOSE 8888

# Command to run the Nextjs development server
# CMD ["npm", "run", "dev", "--port 8888"]
RUN npm run dev --port 8888
