version: '3.8'

services:
  pdf_to_png:
    build: .
    ports:
    - 8000:8000
    volumes:
      - ./data:/app/data
      - ./data_images:/app/data_images
    command: ["python", "app.py"]
    user: appuser