'use client'
import Link from 'next/link';
import Navbar from '@/app/components/NavBar';
import Button from 'react-bootstrap/Button';
import Container from 'react-bootstrap/Container';
import 'bootstrap/dist/css/bootstrap.min.css';
import { useEffect, useRef, useState } from 'react';
import getUserType from '../components/getUserType';
import { Col, Form, FormControl, Row } from 'react-bootstrap';
import main from './gpt';
export default function Tools() {
    /**
     * This page provided the user guide for this project. It also has a ask-ai function that can be used to ask questions about how to use the project. This guide is generated by Claude by providing sparse information.  
    */
    const userGuide = useRef(null);
    const input = useRef(null);
    const [response, setResponse] = useState("");
    const [question, setQuestion] = useState("");
    return (
        <main>
            <Navbar />
            <div className="tw-p-10">
                <Container>
                    <Row>
                        <Col ref={userGuide}>
                            <h1>User Manual</h1>

                            <h2>1. Login Page</h2>
                            <ul>
                                <li>Input username and password</li>
                                <li>Choose "Sign Up" or "Login"</li>
                                <li>New users must verify their email after signing up</li>
                                <li>"Forgot Password" option available</li>
                                <li>After successful login, users are directed to the Dashboard</li>
                            </ul>

                            <h2>2. Dashboard</h2>
                            <p>Displays (non-editable):</p>
                            <ul>
                                <li>Course assignments</li>
                                <li>Personal service hours</li>
                                <li>Department service hours</li>
                                <li>Year-to-date service hours</li>
                                <li>Service hours benchmark</li>
                                <li>SEI result</li>
                                <li>Upcoming events</li>
                                <li>Charts for data visualization</li>
                            </ul>

                            <h2>3. Navigation Bar</h2>
                            <p>Contains:</p>
                            <ul>
                                <li>Dashboard</li>
                                <li>Instructors</li>
                                <li>Courses</li>
                                <li>Service</li>
                                <li>Rules</li>
                                <li>Evaluations</li>
                                <li>Time Tracking</li>
                                <li>Tools (Admin only)</li>
                            </ul>

                            <h2>4. Common Table Features</h2>
                            <ul>
                                <li>Filterable by hovering on table header</li>
                                <li>Options to filter, sort, or hide columns</li>
                                <li>Editable for users with appropriate privileges (head or staff)</li>
                                <li>Charts available for data visualization, showing the same data as tables</li>
                            </ul>

                            <h3>Edit Functions:</h3>
                            <ul>
                                <li>Edit CSV</li>
                                <li>Edit column</li>
                                <li>Edit row</li>
                                <li>Delete record</li>
                                <li>Add new record</li>
                                <li>Upload CSV</li>
                                <li>Download CSV</li>
                            </ul>

                            <h3>CSV Upload Feature:</h3>
                            <ul>
                                <li>When uploading a CSV, the system will display which rows have been changed</li>
                                <li>Users can review these changes before confirming the upload</li>
                            </ul>

                            <h2>5. Instructors Page</h2>
                            <p>Displays:</p>
                            <ul>
                                <li>List of all instructors</li>
                                <li>ID</li>
                                <li>Employee number</li>
                                <li>Email</li>
                                <li>Title</li>
                                <li>Hire date</li>
                                <li>Clicking on an instructor's name navigates to their detailed information page</li>
                            </ul>

                            <h2>6. Courses Page</h2>
                            <p>Displays:</p>
                            <ul>
                                <li>Course information</li>
                                <li>Course assignments</li>
                                <li>Clicking on a course name navigates to detailed course information</li>
                            </ul>

                            <h2>7. Service Rules Page</h2>
                            <p>Features:</p>
                            <ul>
                                <li>Add record</li>
                                <li>Edit CSV</li>
                                <li>Edit column</li>
                                <li>Edit row</li>
                                <li>Delete row</li>
                                <li>Upload CSV</li>
                                <li>Download CSV</li>
                                <li>Clicking on a service role navigates to detailed role information</li>
                            </ul>

                            <h3>Editing a Row:</h3>
                            <ul>
                                <li>Edit information in columns</li>
                                <li>Fields with foreign keys become dropdowns for selection</li>
                            </ul>

                            <h2>8. Tools Page (Admin only)</h2>
                            <ul>
                                <li>Requires Admin key for access</li>
                                <li>Available operations (use with caution):
                                    <ul>
                                        <li>Create new account</li>
                                        <li>Delete account</li>
                                        <li>Change password</li>
                                        <li>View audit log</li>
                                        <li>Export everything as Excel</li>
                                    </ul>
                                </li>
                            </ul>

                            <h2>9. User Profile and Settings</h2>
                            <ul>
                                <li>Click on username/email to access profile</li>
                                <li>Change name and password in profile settings</li>
                            </ul>

                            <h2>10. Data Export</h2>
                            <ul>
                                <li>All users can export their courses into an iCalendar file</li>
                                <li>Admin users can export various data types</li>
                            </ul>

                            <h2>11. Frequently Asked Questions (FAQs)</h2>
                            <ol>
                                <li><strong>How do I reset my password?</strong><br />
                                    Use the "Forgot Password" option on the login page, contact the system admin, or change it yourself in your profile settings.</li>

                                <li><strong>What do I do if I can't access certain features?</strong><br />
                                    Different user roles have different access levels. Contact your system admin if you need additional access.</li>

                                <li><strong>How often is the dashboard updated?</strong><br />
                                    The dashboard updates in real-time.</li>

                                <li><strong>Can I customize the columns in the tables?</strong><br />
                                    Yes, you can filter, sort, or hide columns by hovering your mouse on the table header.</li>

                                <li><strong>What file formats are supported for CSV uploads?</strong><br />
                                    CSV files are supported for uploads.</li>

                                <li><strong>How do I interpret the SEI results on the dashboard?</strong><br />
                                    SEI results are displayed on the dashboard. Contact your administrator for specific interpretation guidelines.</li>

                                <li><strong>What should I do if I notice an error in the data?</strong><br />
                                    Please contact the system admin with detailed information about the error.</li>

                                <li><strong>How can I export specific data from the system?</strong><br />
                                    Currently, only admin users can export most data types. However, all users can export their courses into an iCalendar file.</li>

                                <li><strong>Is there a mobile version of this system?</strong><br />
                                    No, this system is designed for devices with screen sizes of 10 inches or larger. It may not function optimally on smaller devices.</li>

                                <li><strong>Can I schedule recurring events or services?</strong><br />
                                    Only head or staff users can edit events.</li>

                                <li><strong>How do I track my progress towards service hour benchmarks?</strong><br />
                                    The dashboard displays personal service hours, department service hours, year-to-date service hours, and service hours benchmark. Charts are also available for visual tracking.</li>

                                <li><strong>How do I navigate between different pages?</strong><br />
                                    Use the navigation bar at the top of the page to switch between different sections.</li>

                                <li><strong>Can I customize my dashboard view?</strong><br />
                                    No, the dashboard is not customizable at this point.</li>

                                <li><strong>How do I view my service hours history?</strong><br />
                                    Check the dashboard for current statistics. For detailed history, navigate to the Service page.</li>

                                <li><strong>What should I do if I forget my username?</strong><br />
                                    Contact your system administrator for assistance.</li>

                                <li><strong>How can I see upcoming events?</strong><br />
                                    Upcoming events are displayed on the dashboard.</li>

                                <li><strong>Can I print reports from the system?</strong><br />
                                    You can print any page, although the system is not optimized for printing.</li>

                                <li><strong>How do I update my contact information?</strong><br />
                                    Click on your username/email to access your profile, where you can update your information.</li>

                                <li><strong>What do I do if I encounter a technical issue?</strong><br />
                                    Contact your system administrator with details about the issue you're experiencing.</li>
                            </ol>

                            <h2>How To Guide for Common Functions</h2>
                            <ol>
                                <li><strong>How to Log In:</strong>
                                    <ul>
                                        <li>Navigate to the login page</li>
                                        <li>Enter your username and password</li>
                                        <li>Click "Login"</li>
                                    </ul>
                                </li>

                                <li><strong>How to Change Your Password:</strong>
                                    <ul>
                                        <li>Click on your username/email in the top right corner</li>
                                        <li>Select "Profile Settings"</li>
                                        <li>Choose "Change Password"</li>
                                        <li>Enter your current password and new password</li>
                                        <li>Confirm the new password and save changes</li>
                                    </ul>
                                </li>

                                <li><strong>How to View Course Assignments:</strong>
                                    <ul>
                                        <li>Log in to your account</li>
                                        <li>Navigate to the Dashboard or Courses page</li>
                                        <li>Review the course assignments listed</li>
                                    </ul>
                                </li>

                                <li><strong>How to Export Courses to iCalendar:</strong>
                                    <ul>
                                        <li>Navigate to the Courses page</li>
                                        <li>Look for an "Export" or "Download" button</li>
                                        <li>Select the option to export as iCalendar file</li>
                                    </ul>
                                </li>

                                <li><strong>How to Filter Table Data:</strong>
                                    <ul>
                                        <li>Hover your mouse over the table header</li>
                                        <li>Click on the filter icon that appears</li>
                                        <li>Set your desired filter criteria</li>
                                    </ul>
                                </li>

                                <li><strong>How to Edit a Record (for users with appropriate privileges):</strong>
                                    <ul>
                                        <li>Navigate to the relevant page (e.g., Instructors, Courses)</li>
                                        <li>Find the record you want to edit</li>
                                        <li>Click on the "Edit" option (usually represented by a pencil icon)</li>
                                        <li>Make your changes in the editable fields</li>
                                        <li>Save your changes</li>
                                    </ul>
                                </li>

                                <li><strong>How to Upload a CSV:</strong>
                                    <ul>
                                        <li>Navigate to the relevant page</li>
                                        <li>Look for an "Upload CSV" or similar option</li>
                                        <li>Select your CSV file</li>
                                        <li>Review the changes highlighted by the system</li>
                                        <li>Confirm the upload if the changes are correct</li>
                                    </ul>
                                </li>

                                <li><strong>How to View Detailed Information:</strong>
                                    <ul>
                                        <li>For instructors: Click on the instructor's name in the Instructors page</li>
                                        <li>For courses: Click on the course name in the Courses page</li>
                                        <li>For service roles: Click on the role name in the Service Rules page</li>
                                    </ul>
                                </li>

                                <li><strong>How to Access Admin Tools (for admin users only):</strong>
                                    <ul>
                                        <li>Navigate to the Tools page</li>
                                        <li>Enter your Admin key when prompted</li>
                                        <li>Select the desired admin function</li>
                                    </ul>
                                </li>

                                <li><strong>How to View Data Visualizations:</strong>
                                    <ul>
                                        <li>Navigate to the relevant page (e.g., Dashboard, Courses)</li>
                                        <li>Look for chart or graph options, which should display the same data as the tables in a visual format</li>
                                    </ul>
                                </li>

                                <li><strong>How to Print a Page:</strong>
                                    <ul>
                                        <li>Navigate to the page you want to print</li>
                                        <li>Use your browser's print function (usually Ctrl+P or Cmd+P)</li>
                                        <li>Note that the printout may not be optimized for paper format</li>
                                    </ul>
                                </li>
                            </ol>

                            <p>This user guide covers the main features and functionalities of the system. For any additional questions or issues, please contact your system administrator Brian Griffin or the project dev Meg Griffin.</p>
                        </Col>
                        <Col>
                        <h1>Ask AI for help</h1> 
                        <Form>
                        <div className="tw-p-10">{question}</div>
                        <div className="tw-p-10">{response}</div>
                        <FormControl type="text" ref={input} placeholder="Input questions" className="tw-mt-2" />
                        <Button className="tw-mt-2" onClick={async ()=>{
                            setQuestion(input.current.value)
                            setResponse("Loading...")
                            setResponse((await main(input.current.value, userGuide.current.innerHTML)).text)
                            input.current.value = ""
                        }}>Send</Button>
                        </Form>
                        </Col>
                    </Row>
                </Container>
            </div>
        </main>
    );
}
